Invalid Lanes Tag Check Review
Bentleysb/atlas-checks pull request #12
Opened 2018-06-11 17:12 UTC by Bentleysb

This check flags Edges where there is a `lanes` tag with an abnormal value. 

Abnormal values are defined as anything not in the configurable `lanes.filter`.  
The default values are set to `1,1.5,2,3,4,5,6,7,8,9,10`. 

Toll booths are ignored, as they often have an abnormally high number of lanes. 

**OSM Examples:**
1. Way [id:156825478](https://www.openstreetmap.org/way/156825478) is flagged correctly by this check as a highway with no lanes.
2. Way [id:247311654](https://www.openstreetmap.org/way/247311654) is connected to a toll booth and has a high but valid number of lanes. It is not flagged.

2018-06-12 00:21 UTC, danielduhh reviewed
Hey B - here's my first pass at review

2018-06-12 00:21 UTC, danielduhh commented on config/configuration.json
> -   "DuplicatePointCheck": {
This shouldn't have been updated  - lets set it back to its original formatting

2018-06-12 00:21 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        while (!toProcess.isEmpty())
Is it necessary to loop through all connectedEdges' connectedEdges and connectedNodes? That can be expensive.... is it adequate to just check the incoming edges connected edges and nodes?

Also, whenever `toolBooth` is true, we should break out of the queue

2018-06-12 00:21 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +
nit: extra space

2018-06-12 00:21 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +
nit: extra space

2018-06-12 16:05 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        while (!toProcess.isEmpty())
It is necessary to loop through all connected edges and nodes because there can be a large amount of lanes on on both sides of the toll booth. For any given edge, I don't know if I need incoming or out going edges to find a connected toll booth. 

I believe it is more efficient to not break the while loop/queue when `tollBooth` is true. This is because I am collecting all the edges connected to that toll booth in one pass and then adding them to a class level set that is checked in `validCheckForObject`. So for any toll both I am only looping through the entire check once instead of as many times as there are high lanes count edges connected to the toll booth.

2018-06-12 16:14 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        while (!toProcess.isEmpty())
One improvement made so nodes are not checked after toll booth node is found.

2018-06-13 00:25 UTC, danielduhh requested changes

2018-06-13 00:25 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        return Validators.hasValuesFor(object, LanesTag.class)
Does it make sense to process non-navigable highway tags?

2018-06-13 00:25 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        return Validators.hasValuesFor(object, LanesTag.class)
We can get away with moving the tag value filter logic here. That way, when we get into the `flag` function, we already know our Edge has an invalid tag

```java
object instanceof Edge
      && HighwayTag.isCarNavigableHighway(object)
      && Validators.hasValuesFor(object, LanesTag.class)
      && !this.lanesFilter.test(object);
```

2018-06-13 00:25 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        while (!toProcess.isEmpty())
Looks like we want this function to do two things..
A) Find all connected Edges with _the same_ invalid lane tag values that are connected to the incoming object.
B) Return true if any of these connected Edges have a Node with the `barrier=toll_booth`

I think it would be a good idea to split these into two functions

2018-06-13 17:06 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +        return Validators.hasValuesFor(object, LanesTag.class)
Changed to filter out non navigable highway tags and valid lanes tags.

2018-06-18 05:36 UTC, danielduhh requested changes
Nice work - this is my last comment. You'll have to update documentation afterwards

2018-06-18 05:36 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +                            .forEach(validEdge -> this.isChecked.add(validEdge.getIdentifier()));
Instead of creating a Set to keep track of Edges you've processed, you can just mark them as flagged with the global `this.markAsFlagged` function. That way, in `validCheckForObject`, you won't both `this.isChecked` and `this.isFlagged`

2018-06-18 16:20 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +                            .forEach(validEdge -> this.isChecked.add(validEdge.getIdentifier()));
I choose to keep `isChecked` and use it to mark processed items **not** connected to a toll booth (it contained items connected **to** a toll booth before). `isFlagged` now works to test for flagged items and items connected to a toll booth. The `flag` method of this check now checks `isChecked` before running `partOfTollBooth`. This way each edge cannot be processed through the expensive `partOfTollBooth` more than once.

2018-06-18 18:55 UTC, danielduhh approved these changes
Nice work - added a small "nice to have" 😉

2018-06-18 18:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +            for (final Edge edge : polledEdge.connectedEdges())
nice to have: I think `connectedEdges()` returns the reversed Edge on two-way roads. We could eliminate the amount of loop here if we filtered with `isMasterEdge`

2018-06-18 19:12 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +            for (final Edge edge : polledEdge.connectedEdges())
Do you think there would be any problem filtering with `isMasterEdge` both here and in `validCheckForObject`?

2018-06-18 19:20 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/InvalidLanesTagCheck.java
> +            for (final Edge edge : polledEdge.connectedEdges())
No I don't think so

2018-06-18 21:00 UTC, closed without merging