Overlapping AOI Polygon Check Review
Bentleysb/atlas-checks pull request #14
Opened 2018-06-20 20:49 UTC by Bentleysb

This check flags polygons that overlap and represent the same Area of Interest (AOI).

AOIs are defined through the configurable value `aoi.tags.filters`. This is a list of tag filters.  
If a polygon has any of the tags in any of the filters, it is considered an AOI.  
If two overlapping AOIs both have tags in the same filter, they are flagged as representing the same thing.

**OSM Examples:**

1. Way [id:23182647](https://www.openstreetmap.org/way/23182647) overlaps way [id:301044293](https://www.openstreetmap.org/way/301044293) and they are both tagged as `landuse=cemetery`.
2. Way [id:203547456](https://www.openstreetmap.org/way/203547456), tagged as `natural=wood`, overlaps way [id:546230157](https://www.openstreetmap.org/way/546230157), tagged as `landuse=forest`, both tags are representing the same AOI.

2018-06-27 17:59 UTC, danielduhh requested changes
A couple nits and questions for clarification

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +    private static final List<String> AOI_FILTERS_DEFAULT = Arrays.asList(
Whats the purpose of making this an array, and then converting it to a `TaggableFilter`? Couldn't we just make this a `TaggableFilter` to begin with?

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +        this.aoiFiltersString = (List<String>) configurationValue(configuration, "aoi.tags.filters",
This `aoiFiltersString` isn't actually used anywhere by this constructor

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +        return object instanceof Area && (aoiFiltersTest(object))
We want to avoid calling any functions that iterations in `validCheckForObject`

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +
nit: whitespace

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +
nit: whitespace

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +
nit: whitespace

2018-06-27 17:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +
nit: whitespace

2018-06-27 19:26 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +    private static final List<String> AOI_FILTERS_DEFAULT = Arrays.asList(
It is being made into a **list** of `TaggableFilter`s, thus it is list of strings to define the filters with.

2018-06-27 19:31 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/areas/OverlappingAOIPolygonCheck.java
> +        return object instanceof Area && (aoiFiltersTest(object))
The only iteration is to call the test method of `TaggableFilter`s. `validCheckForObject` often contains tests against `TaggableFilter`s, this just does it in a slightly dynamic fashion.

2018-07-03 17:30 UTC, danielduhh approved these changes
let it fly

2018-07-03 17:32 UTC, closed without merging