Mixed Case Name Check Review
Bentleysb/atlas-checks pull request #16
Opened 2018-06-29 22:57 UTC by Bentleysb

This check flags objects with name tags that improperly use mixed cases.

Proper case use is defined by set standards and configurable exceptions. 

The standards are as follows:

* Words must start with a capital unless:
    * There are no other words in the name
    * The first letter is preceded by a number
* All other letters must be lower case unless: 
    * They follow an apostrophe and, they are not the last letter of the word
    * The entire word is uppercase, except the last letter if it follows or is followed by an apostrophe

The standards are broken by the following configurable exceptions (with default values):

* Articles that are capitalised only if they are the first word:
    * a
    * an
    * the
* Prepositions that do not need to start with a capital:
    * and
    * from
    * to
    * of
    * by
    * upon
    * on
    * off
    * at
    * as
    * into
    * like
    * near
    * onto
    * per
    * till
    * up
    * via
    * with
    * for
    * in
* Name affixes that may be followed by a capital:
    * Mc
    * Mac
    * Mck
    * Mhic
    * Mic
    
These configurables allow this check to be adapted to test different languages.  
OSM uses the `name` tag for the name in a locations primary language, and `name:[ISOcode]` for other languages.
This check uses two configurable to control what languages are checked.

The first is a list of ISO codes for countries that should have there `name` tag checked. It has default values of:

* AIA
* ATG
* AUS
* BHS
* BRB
* BLZ
* BMU
* BWA
* VGB
* CMR
* CAN
* CYM
* DMA
* FJI
* GMB
* GHA
* GIB
* GRD
* GUY
* IRL
* JAM
* KEN
* LSO
* MWI
* MLT
* MUS
* MSR
* NAM
* NZL
* NGA
* PNG
* SYC
* SLE
* SGP
* SLB
* ZAF
* SWZ
* TZA
* TON
* TTO
* TCA
* UGA
* GBR
* USA
* VUT
* ZMB
* ZWE

The second is a list of `name:[ISOcode]` tags to check. Default values are:

* name:en

A final configurable is a list of characters that names are split by to for words. Its default values are: 

* SPACE
* \-
* /
* (
* )
* &
* @
* –

**OSM Example:**
1. Way [id:4780932622](https://www.openstreetmap.org/node/4780932622) has the name `NZ Convenience store`. It is flagged because the S in store should be capitalized.

2018-07-11 00:17 UTC, danielduhh requested changes
Great stuff B - here are some minor comments to start

2018-07-11 00:17 UTC, danielduhh commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
change to "countries" -> see https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/distributed/IntegrityCheckSparkJob.java#L81

2018-07-11 00:17 UTC, danielduhh commented on config/configuration.json
> +    "name.language.keys":["name:en"],
We should logically group these keys; for example
```json
"name":{
  "language.keys",
  "affix",
  "prepositions",
  "articles",
  "units"
}, 
"regex.split": ""
```

2018-07-11 00:17 UTC, danielduhh commented on docs/checks/mixedCaseNameCheck.md
> +* Prepositions that do not need to start with a capital:
Let's replace these long bullet points with comma separated lists.

2018-07-11 00:17 UTC, danielduhh commented on docs/checks/mixedCaseNameCheck.md
> +* AIA
See above about comma separated lists

2018-07-11 00:17 UTC, danielduhh commented on docs/checks/mixedCaseNameCheck.md
> +# Mixed Case Name Check
Continuing the discussion around duplicating code in these high level reviews... I agree with Mike in that we should not have snippets of complex functions, but instead point them to where they exist in the checks code. Instead, we can highlight a few interesting, or essential lines of code we deem relevant.

2018-07-11 00:17 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +            mixedCaseNameTags.add("name");
Use `NameTag.key`

2018-07-11 00:17 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +            if (object instanceof LocationItem)
this can be one line: `String osmFeatureType = object instance of LocationItem ? "Node" : "Way"`

2018-07-11 00:17 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (checkNameCountries.contains(object.tag(ISOCountryTag.KEY).toUpperCase())
Isn't this ISO code checked in `validCheckForObject` ?

2018-07-11 00:17 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        return !(object instanceof Relation) && !this.isFlagged(object.getOsmIdentifier())
After updating the config to use countries, you can replace this with `object.getTag(ISOCountryTag.KEY).isPresent()`

2018-07-11 15:48 UTC, Bentleysb commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
`"countries"` will automatically filter out objects that do not have an ISO code in its list?

2018-07-11 16:41 UTC, danielduhh commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
Yeah - this check shouldn't apply to non-English speaking countries

2018-07-11 16:50 UTC, Bentleysb commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
It is set up so it can support any language if the configurables are set properly. Any language that it is set to support can then be checked in any country by adding the right tag to `name.language.keys`. This list is to tell the check which countries the set languages are native to, so that it will check the `name` tag as well as the `name:[ISOcode]` tags, in `name.language.keys`, for those countries.

2018-07-11 16:56 UTC, Bentleysb commented on docs/checks/mixedCaseNameCheck.md
> +# Mixed Case Name Check
How does it look now?

2018-07-11 17:25 UTC, danielduhh commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
Would that be conflicting w/ prepositions, articles, and name affix's? Let's say we have `name:es, name:en` in `name.language.keys` that used the same list of articles/prepositions as `name:en`.

2018-07-11 19:09 UTC, Bentleysb commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
It could be conflicting if a preposition, article, affix, or unit exists in both languages but was only a preposition, article, affix, or unit in one of them. I don't think that should occur very often.

2018-07-20 17:58 UTC, savannahostrowski requested changes
Great start @Bentleysb! 👨‍💻 

A few comments to help satisfy memory constraints and improve readability.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        return !(object instanceof Relation) && !this.isFlagged(object.getOsmIdentifier())
I'd throw comments between each conditional to briefly (in one line) describe what each one is filtering out.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (checkNameCountries.contains(object.tag(ISOCountryTag.KEY).toUpperCase())
I think this has already been verified in the preliminary filtering. I'd recommend trying to filter as much out as possible in the `validCheckForObject` to try and minimize the runtime of this check.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (!mixedCaseNameTags.isEmpty())
Why do you need to collect all the objects into an array? You should be able to flag each one as it's read in. Using an array to store all the entities is also really memory intensive (we're dealing with what is essentially big data here) so you should avoid storing objects at all costs.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                        if (firstLetterMatcher.find()
A good rule of thumb is to never return a boolean from a conditional. You can simplify this logic by just returning the result of the conditional itself.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                    if (Pattern.compile("\\p{Ll}").matcher(word).find()
Same here. Just return the result of the conditional.

2018-07-20 17:58 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                if (!Pattern
Something that will make this check more readable would be to move each of the conditionals into their own helper methods to make this method easier to read. 

You could then have methods like `isAllLowerCase()` etc. which are super descriptive.

2018-07-20 18:32 UTC, Bentleysb commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
@danielduhh, do you think this is an acceptable edge case? I would like to keep the ability for this to be multilingual, but if that is not going to work I need to deal with it before tackling some of the other changes.

2018-07-23 16:25 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        return !(object instanceof Relation) && !this.isFlagged(object.getOsmIdentifier())
When I do this, I get conflicting errors from checkstyle and spotless. Checkstyle wants the comments indented and spotless does not. Should I make an issue on osmlab/atlas-checks for this?

2018-07-23 16:31 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (checkNameCountries.contains(object.tag(ISOCountryTag.KEY).toUpperCase())
This may be irrelevant, depending on what we decide to do about multi-lingual support. However, as it currently stands this is not necessarily verified in `validCheckForObject`. In `validCheckForObject` it is in an or statement that test if there is ISO tag and name tag or a language specific name tag. It could be that an object only has one of the language specific name tags, so the iso and name tags have to be checked for again here.

2018-07-23 16:38 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        return !(object instanceof Relation) && !this.isFlagged(object.getOsmIdentifier())
Mmm, that's odd. I've never had that happen before.

Here's an example of it when it passes all the linters -> https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/DuplicateWaysCheck.java

Maybe it's a matter of keeping all the conditionals on their own line? If you've already tried this way of styling it, let me know and we can chat!

2018-07-23 16:40 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (!mixedCaseNameTags.isEmpty())
I am not collecting the objects, just the tag keys that are mixed case. I use this list in the instructions to indicate exactly where the problems are. I could create a string that I keep appending to, instead of a list that I join, if that would be more efficient.

2018-07-23 18:33 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                        if (firstLetterMatcher.find()
I am just going to leave this as is. I like the readability of the logic flow.

2018-08-02 15:59 UTC, danielduhh requested changes
Sorry it's taken forever to keep the review going. I added a few comments and tagged you in an older one

2018-08-02 15:59 UTC, danielduhh commented on docs/checks/mixedCaseNameCheck.md
> +# Mixed Case Name Check
We can do away with all 3 functions code blocks. You did a great job of explaining whats going on in the intro summary. See comment about replacing large bullet point list w/ a comma separated list

2018-08-02 15:59 UTC, danielduhh commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
Yeah, do you have a test for that particular edge case? I think multilingual support is great

2018-08-02 15:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +        if (checkNameCountries.contains(object.tag(ISOCountryTag.KEY).toUpperCase())
If I understand correctly; the OR conditional checks objects that have a `name`, `iso`, and the country exists in list OR has a language name tag (`name:en`)?

2018-08-02 15:59 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +            mixedCaseNameTags.add("name");
@Bentleysb

2018-08-02 16:16 UTC, savannahostrowski requested changes
LGTM - still one outstanding comment.

Please re-consider refactoring anywhere where you are return true or false explicitly. Best practice is to just return the conditional itself. Your code will really benefit in terms of readability by doing this.

2018-08-02 16:16 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                        if (firstLetterMatcher.find()
I would really still encourage you to  return the conditionals themselves. This will simplify your code.

2018-08-02 21:50 UTC, Bentleysb commented on config/configuration.json
> +    "check_name.countries":["AIA", "ATG", "AUS", "BHS", "BRB", "BLZ", "BMU", "BWA", "VGB",
I have unit tests for multilingual support. I do not have one to test for the edge case because it would fail by design.

2018-08-02 21:56 UTC, Bentleysb commented on docs/checks/mixedCaseNameCheck.md
> +# Mixed Case Name Check
I think you may be looking at an older version of this.  The long bulleted lists are gone and the functions have been separated. Let me know if we can still get rid of any of the code review portions.

2018-08-02 22:03 UTC, danielduhh commented on docs/checks/mixedCaseNameCheck.md
> +# Mixed Case Name Check
Ah yes I was 0 looks good, however, still to many code blocks. Pick your favorite out of the remaining. You can keep the descriptions of the others if it makes sense. Great tutorial btw

2018-08-02 22:30 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                        if (firstLetterMatcher.find()
I have just been trying to do this, without success. I cannot directly return the values, because if they are false the rest of the `wordArray` values will not be checked. I am essentially creating an any match loop. I did try using `stream` and `anyMatch`, but that does not allow me to use the `firstWord` variable that is used to vary what happens the first time through. So without completely redoing the method I am not sure this is possible. However, I was able to condense a number of the conditionals into one.

2018-08-08 00:18 UTC, danielduhh approved these changes

2018-08-08 00:18 UTC, danielduhh commented
When you get a chance, add one or more examples to the PR description

2018-08-08 00:45 UTC, savannahostrowski approved these changes
I think this could still be improved by returning the results of the conditional statements...This may or may not require a pretty significant refactor though.

However, I appreciate the conditional condensing/clean up you did! If you're happy with this, then LGTM! 😸

2018-08-08 00:49 UTC, danielduhh commented
@savannahostrowski I may have missed that discussion. Is that regarding the validCheckForObject function ?

2018-08-08 01:07 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java
> +                        return true;
@danielduhh yeah, I think the discussion happened when you were in Milan. My comment was this method and specifically this part where we are specifically returning  true and false. It's generally better practice to return the result of the conditional statement because we aren't really doing anything else here except returning. Again, this has been cleaned up a lot. However, my inclination is that we could probably further simplify this logic.

2018-08-08 15:45 UTC, Bentleysb commented
@danielduhh, there is one example in the description, but I will see if I can find some of the stranger cases to show.

2018-08-08 22:18 UTC, closed without merging