One Member Reletion Enhancement Review
Bentleysb/atlas-checks pull request #17
Opened 2018-08-03 21:53 UTC by Bentleysb

This enhancement is to fix an issue where flags with empty geometries were being created. This was occurring when a relation with another relation as its only member was flagged. 

Now in these situations the geometry of the nested relations is recursively gathered, to show what the relation represents, and the situation is noted in the instruction.

2018-08-16 03:23 UTC, danielduhh requested changes
Nice work - had some questions for clarification

2018-08-16 03:23 UTC, danielduhh commented on src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
> +    public Atlas oneMemberRelationRelationAtlas()
nit: testOneMemberRelationRelationAtlas()

2018-08-16 03:23 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
> +    private Set<AtlasObject> getRelationMembers(final Relation relation)
For clarity, every time you encounter a Relation w/ a member that is a Relation, you recursively fetch each said Relation's members to use, creating somewhat of a tree of members?

If this is true, can we make this clear in the comments. Also, we should check w/ one of the analysts to see if this makes sense...

2018-08-16 03:24 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
> +    private Set<AtlasObject> getRelationMembers(final Relation relation)
@MonicaBrandeis @kkonishi2

2018-08-16 16:05 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
> +    private Set<AtlasObject> getRelationMembers(final Relation relation)
It is not really a tree, as the ultimate return is a single set of AtlasObjects that are the members of all relations found. So while it searches a tree for relations, the output is flat.

2018-08-16 16:41 UTC, savannahostrowski requested changes

2018-08-16 16:41 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
> +    private Set<AtlasObject> getRelationMembers(final Relation relation)
Spoke offline about implementing BFS or DFS here to reduce time complexity to O(n).

2018-08-16 17:27 UTC, Bentleysb commented on src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
> +    public Atlas oneMemberRelationRelationAtlas()
This is intentional, as it is testing a one member relation with a relation as its one member.

2018-08-16 17:29 UTC, danielduhh commented on src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
> +    public Atlas oneMemberRelationRelationAtlas()
Yeah, test methods should start with `test` :)

2018-08-16 17:33 UTC, Bentleysb commented on src/test/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheckTestRule.java
> +    public Atlas oneMemberRelationRelationAtlas()
Oh, yep. I just read over that.

2018-08-22 23:30 UTC, savannahostrowski approved these changes
👑 YES! LGTM.

2018-08-22 23:30 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/validation/relations/OneMemberRelationCheck.java
> +    private Set<AtlasObject> getRelationMembers(final Relation relation)
@Bentleysb This is rad! Nice work implementing BFS!

2018-08-28 23:35 UTC, danielduhh commented
LGTM thanks :)

2018-08-28 23:35 UTC, danielduhh approved these changes

2018-08-28 23:40 UTC, closed without merging