Flag File Diff Commands
Bentleysb/atlas-checks pull request #18
Opened 2018-09-05 21:52 UTC by Bentleysb

This adds command style tools for diffing geojson and log flag files. It also adds the `AtlasChecksCommand` class to run these tools from. This is built to replicate the structure of Atlas commands/sub-commands. 

The diffing commands take 2 sets of their associated files, as comma separated paths, and an optional output directory path. They will then report the number of unique flags, and the flags added, changed and subtracted from the source to target files. If the output folder is specified the altered flags will be written to files in that directory. 

The diff commands have been abstracted to use a base class. This has eliminated a lot of redundant code, but has cased me to use some unchecked casts and calls. If there is a better way to handle this I would love to hear it. Of course any other suggestions are welcome as well.

2018-09-06 04:46 UTC, savannahostrowski requested changes
Nice work @Bentleysb! Left ya some comments regarding code design!

Let me know if you want to chat about any of my comments! 😺

2018-09-06 04:46 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
Using booleans as arguments for a method isn't the best pattern as it's not very descriptive (especially when reading function calls). For example, imagine that someone adds some more booleans to the method's params. Over time, your function call could look something like `getMissingAndChanged(someHashmap, someOtherHashmap, true, false, true, true, false, true)`. 🙃 

Additionally, the implementation of this method in the other classes returns missing and/or changed. I would suggest breaking this method into two methods - one for missing and one for changed so it's less ambiguous. You could also implement a new class for your MissingAndChanged object which has a missing attribute and a changed attribute. This way it's super clear to the reader what's going on.

2018-09-06 04:46 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +        // Get changes from source to target
With the refactor mentioned below, we could avoid the `.get(0)` type function.

2018-09-06 04:46 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +        final HashSet<JsonObject> subtractions = subAndChange.get(0);
These types of statements aren't clear to the reader what is at index 0 or 1.

2018-09-07 22:55 UTC, danielduhh requested changes
This is pretty awesome and super fast! Had an issue generating the output file & minor comments

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +package org.openstreetmap.atlas.checks.commands;
nit: can you name it `AbstractJSONFlagDiffCommand` (capitalize JSON)

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +        json.get("features").getAsJsonArray().forEach(feature -> map
We should put all of these json specific key names in constant variables

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +                    ((JsonObject) feature).get("properties").getAsJsonObject()
See above about using constants for geojson key names

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +package org.openstreetmap.atlas.checks.commands;
https://jsonformatter.org/ for removing whitespace and new lines

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +            csv -> Stream.of(csv.split(",")).collect(Collectors.toSet()),
csv ?

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +                object -> sourceIds.add(object.getAsJsonObject().get("ItemId").getAsString()));
"ItemId" should be a constant

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
Could create an `ADDED`, `REMOVED`, `CHANGED` (or something similar) enum set and use that for your conditional checks

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    private static final Command.Switch<Set<String>> SOURCE_FILE_PARAMETER = new Command.Switch<>(
Source and target could be simplified if we just accepted either a file or directory. This way, you could use `Path` and wouldn't need to covert to a set

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    private static final Command.Switch<String> OUTPUT_FOLDER_PARAMETER = new Command.Switch<>(
Was able to generate log stats, by my test didn't output a file. My commands are ->
```
geoJSON-diff -source=/Users/danielbaah/github/atlas-checks/build/geojson/ATG/FloatingEdgeCheck-1536355635986-20.geojson -target=/Users/danielbaah/github/atlas-checks/build/geojson/ATG/FloatingEdgeCheck-1536355572891-8.geojson output=/Users/danielbaah/github/atlas-checks/diff-results/
```

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
Would also consider changing this function name to `compare`

2018-09-07 22:55 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksLogDiffSubCommand.java
> +                final String checkName = source.get("properties").getAsJsonObject().get("generator")
See above about enum set

2018-09-07 23:15 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    private static final Command.Switch<String> OUTPUT_FOLDER_PARAMETER = new Command.Switch<>(
`output` -> `-output`

2018-09-10 16:52 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
I am not sure I follow on how enums are useful here.

2018-09-10 16:53 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +            csv -> Stream.of(csv.split(",")).collect(Collectors.toSet()),
They are comma separated values, but perhaps that is confusing with the file type.

2018-09-10 17:17 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
@Bentleysb Enums are another approach that would prevent you from passing in booleans to the method. It would be less ambiguous because you'd be able to see exact what params are being passed in.

2018-09-10 21:21 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
I ended up going with using an enum for the function parameter, and a new class being returned. I went with this approach to  keeps the general structure close to what it was. This meant that I could continue to override the method and keep to only 2 for loops while gathering the 3 HashSets.

2018-09-12 06:44 UTC, danielduhh requested changes
This thing is looking prime! Had a question and some nits

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJSONFlagDiffSubCommand.java
> +        final HashSet<JsonObject> additions = getDiff(this.target, this.source, DiffReturn.MISSING)
nit: use `this.` when referencing class functions

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJSONFlagDiffSubCommand.java
> +        final JSONFlagDiff subAndChange = getDiff(this.source, this.target, DiffReturn.CHANGED);
nit:`this.`

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +            else if (returnType.equals(DiffReturn.CHANGED) && !identicalFeatureIds(
nit: `this.identicalFeatureIds`

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJSONFlagDiffSubCommand.java
> +    protected boolean identicalFeatureIds(final JsonArray sourceArray, final JsonArray targetArray)
Curious, why's this return true by default ?

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +            else if (returnType.equals(DiffReturn.CHANGED) && !identicalFeatureIds(
Also, the parameters passing in are pretty hard to read; would be worth breaking them out into individual variables before passing them into `this.identicalFeatureIds `

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJSONFlagDiffSubCommand.java
> +public abstract class AbstractJSONFlagDiffSubCommand implements FlexibleSubCommand
I don't think you need the `Abstract` prefix

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> + * written to new geoJSON files.
Would be worth noting what's defined as an "update"

2018-09-12 06:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksLogDiffSubCommand.java
> + * Takes 2 sets of atlas-checks log files and reports the number of additions, subtractions, and
Would be worth noting what's defined as an "change"

2018-09-12 06:44 UTC, danielduhh commented on src/test/resources/org/openstreetmap/atlas/checks/commands/source/geo_11.geojson
> +{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"GeometryCollection","geometries":[{"type":"MultiLineString","coordinates":[[[96.1306485,16.810537],[96.1322355,16.8113359
`src/test/resources/org/.../checks/commands/source/` and `/target` gets is turned into a package here. Because those packages don't actually exist in `/src`, it's misleading. Can you just update the file name to contain source/target

2018-09-12 16:25 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AtlasChecksGeoJSONDiffSubCommand.java
> +            else if (returnType.equals(DiffReturn.CHANGED) && !identicalFeatureIds(
To break the parameters into variables, I would have to put the `!this.identicalFeatureIds()` part of this conditional in its own nested if statement. If that seems cleaner, I can do it.

2018-09-12 16:29 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJSONFlagDiffSubCommand.java
> +    protected boolean identicalFeatureIds(final JsonArray sourceArray, final JsonArray targetArray)
This returns true by default because that indicates no change in the Atlas ids. If it was the opposite, every flag that was in both sets of files would be reported as changed.

2018-09-12 16:33 UTC, Bentleysb commented on src/test/resources/org/openstreetmap/atlas/checks/commands/source/geo_11.geojson
> +{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"GeometryCollection","geometries":[{"type":"MultiLineString","coordinates":[[[96.1306485,16.810537],[96.1322355,16.8113359
I need the files to be in folders to test the multi file handling, now that we accept directories instead of sets of paths. I suppose I could make temp folders and copy the files there to run them, but that seems like a lot of extra work to run tests.

2018-09-12 21:28 UTC, savannahostrowski requested changes

2018-09-12 21:28 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +        final HashSet<JsonObject> additions = getMissingAndChanged(this.target, this.source, true)
This is still kind of hacky. 

This isn't really descriptive of what is at the 0th or 1st index of the returned value. The reason I suggested refactoring to use a class to represent the missing and changed object was with the intention that you could use a getter to get these instead of `.get(0)` so it would be more clear.

2018-09-12 21:28 UTC, savannahostrowski commented on src/main/java/org/openstreetmap/atlas/checks/commands/AbstractJsonFlagDiffSubCommand.java
> +    protected ArrayList<HashSet<JsonObject>> getMissingAndChanged(final HashMap source,
^This approach fixes a part of the ambiguity but doesn't address my comment above.

2018-09-12 21:29 UTC, savannahostrowski commented
Ahhh, some how I commented on old code. This looks a lot better. Ignore the above comments. 🙃

2018-09-12 21:30 UTC, savannahostrowski approved these changes

2018-09-17 16:38 UTC, danielduhh approved these changes
Looks great... my only wish is that you change the flex command from `geoJSON-diff` to `geojson-diff` 🙏

2018-09-17 22:03 UTC, closed without merging