EdgeCrossingEdgeCheck Bug Fix & Enhancements
Bentleysb/atlas-checks pull request #21
Opened 2018-10-24 18:25 UTC by Bentleysb

### Description:

This fixes a bug created by a change of a `LayerTag` method (see https://github.com/osmlab/atlas-checks/issues/77). The check was dependent on the default value the previous method granted. This default has been re-added, though it now takes into account the difference between a bad and non-existent layer tag. This bug should have been caught by the unit tests, but were missed due to a lack of car navigable highway tags. Unit test have been updated to address this.

This PR also includes a change to eliminate redundant flags and a new filter for highway classifications. The new filter was added to eliminate false positives from lower classification roads that can commonly cross. The redundant flags were caused by the check looking at the crossings of a single Edge and then having one of the crossing Edges have another crossing of its own that was found later. This situation was eliminated by using a BFS walker to find all connected invalid crossings. 

### Potential Impact:

Remove a large number of false positives.

### Unit Test Approach:

Unit tests were updated so that all edges have car navigable highway tags. This prevents them from being filtered out in validCheckForObject.
Some unit tests had their expected flag object count changed to reflect the new redundant flag elimination logic. 

### Test Results:

Testing showed false positive rates dropped back to expected levels after the `LayerTag` method fix. Continued testing showed another minor drop after implementing the de-duplication enhancement, but only due to flags being combined.

2018-10-24 20:02 UTC, nachtm approved these changes
Nice work @Bentleysb! I have a nit, two questions and an unrelated comment:

2018-10-24 20:02 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +public class EdgeCrossingEdgeCheck extends BaseCheck
nit: `BaseCheck<Long>`?

2018-10-24 20:02 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +                    ? LayerTag.getTaggedValue(edge) : Optional.of(0L);
nit/question: should `0L` be pulled out into a constant? I see it both ways -- 0 is a small enough number that it's not really a magic number, but it also has a semantic meaning as `OSM_DEFAULT` or something like that. Thoughts?

2018-10-24 20:02 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +            // MapRoulette will display way-sectioned edges in case there is an invalid crossing.
I'm not super familiar with MapRoulette's display, so I want to clarify. MapRoulette is given the explicit coordinates for a particular edge and not just the OSM ids, right? So what you're saying is that the same OSM id may be mentioned multiple times, but the actual crossings displayed will be different?

2018-10-24 20:02 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +        while (!toCheck.isEmpty())
Nice BFS! This is unrelated to this PR in particular, but I've noticed a couple of instances in which BFS is getting re-implemented. Would it be worthwhile to create some kind of utility function or class?

2018-10-24 20:03 UTC, sayas01 approved these changes
Good job Bentley!

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
nit: extra line

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
extra line

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +
extra line

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +                return HighwayTag.isCarNavigableHighway(highway.get())
As highway.get() is fetched three times, it would be good to use a variable for this.

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +
extra line

2018-10-24 20:03 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +                    {
`continue` statement can be removed by checking if the value returned is false, then do `invalidEdges.add(crossingEdge);` and ` toCheck.add(crossingEdge);`

2018-10-24 20:28 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +public class EdgeCrossingEdgeCheck extends BaseCheck
I think its fine leaving this. Lots of checks don't explicitly define this and just use the default Long.

2018-10-24 20:31 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +            // MapRoulette will display way-sectioned edges in case there is an invalid crossing.
This comment isn't actually mine, but got moved in the conversion to BFS. However, you are correct that you might have say 3 flag objects all with the same osm id that display several different crossings. This is the same as the geojson and log outputs for the most part. The point is just that a regular OSM editor might be confused because we are using edges.

2018-10-24 20:33 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +        while (!toCheck.isEmpty())
A good point. We do seem to use BFS as simple Edge walkers quite often. It is probably worth looking into making a utility out of that.

2018-10-24 20:34 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
I like to separate my static from non static globals.

2018-10-24 20:35 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
separating variables

2018-10-24 20:38 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +                    {
Nice catch. Implemented.

2018-10-24 21:55 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +public class EdgeCrossingEdgeCheck extends BaseCheck
[Choosing to use raw types is generally a bad idea](https://stackoverflow.com/questions/2770321/what-is-a-raw-type-and-why-shouldnt-we-use-it) since you don't get any type guarantees. It's not a huge deal in this case, since everything else is structured well, but I think it's smart to use good practices anyways.

2018-10-25 16:57 UTC, danielduhh requested changes
Nice job & thanks everyone for reviewing. Had a suggestion about your BFS in the `flag()` function

2018-10-25 16:57 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/EdgeCrossingEdgeCheck.java
> +        while (!toCheck.isEmpty())
I would consider breaking this BFS into a helper function

2018-10-31 01:05 UTC, danielduhh approved these changes

2018-10-31 01:06 UTC, danielduhh commented
Nice work !

2018-10-31 15:32 UTC, closed without merging