DNM - Roundabout Revamp
Bentleysb/atlas-checks pull request #25
Opened 2018-11-27 19:17 UTC by Bentleysb

### Description:

- [ ] Depends on atlas 5.2.7+

This pr is to consolidate and enhance the existing roundabout checks (MalformedRoundabout, RoundaboutValance, and ClosedLoopRoundabout). Previous to this pr, these checks heavily overlapped both in code and flags, with ClosedLoop being almost entirely redundant. As such, the functionality has been consolidated into Malformed and Valance, while abstracting out duplicate code. 
Malformed now checks for directionality, non-valence routing, and overlapping or enclosed edges. Valance now check both node and overall valence. ClosedLoop is entirely redundant and can be deprecated. 
In addition to consolidation, both checks have been enhanced with new or altered features. Both now use [SimpleEdgeWalker](https://github.com/osmlab/atlas/blob/dev/src/main/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalker.java) to gather all edges in a roundabout. Valance now filters out any non-car navigable edges, as these edges often don't follow the same valence rules. Malformed has enhanced direction detection by using the Route class to build a polyline from the set of Edges, and using an average direction to allow for stranger shaped roundabouts. Malformed also has all new intersecting/enclosed edge detection to find miss-mapped ways and throughabouts.  

For more information and examples of what each check flags, please see the updated .md docs for each check. 

### Potential Impact:

Negligible 

### Unit Test Approach:

Malformed's unit test were updated to include highway tags. There were also a large number added to test the newly added functions. 
Valance's unit test were heavily reworked to accommodate node valance testing. All coordinates have been redone, junction tags added, and extra tests created for node valance testing. 

### Test Results:

Extensive testing and comparison against old results shows that all old true positives remain, while many false positives and false negatives are now handled correctly. Sampled results from 20 countries showed a near 0% false positive rate for both checks.

2018-12-10 19:08 UTC, sayas01 requested changes
Hi @Bentleysb ! Awesome job with the consolidation and enhancements! Looks pretty neat to me. I just have a few comments on code formatting.

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +    private static final String COMPLETE_ROUTE_INSTRUCTIONS = "This roundabout does not form a single, one-way, complete, car navigable route.";
nit : Won't `INCOMPLETE_ROUTE_INSTRUCTION` makes more sense?

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        return polygon.intersections(polyline).stream()
`polygon.intersections(polyline).stream().anyMatch()` can be used in place of filter.

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +    public static final String WRONG_VALENCE_INSTRUCTIONS = "This roundabout has the wrong valence. It has a valence of {1,number,#}.";
Is there a reason why these strings are Public?

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +     * Function for {@link SimpleEdgeWalker} that gathers connected edged that are part of a
typo : `edges`

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +        // CHeck the valence of each node and gather the total valence
nit: Check

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +                    .filter(currentEdge -> !roundaboutEdges.contains(currentEdge))
This could be made compact by replacing the various filters with a single filter and combining the conditions with `&&`.

2018-12-10 19:08 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
>          // or greater than or equal to the maximum configured number of connections
We may need to update this.

2018-12-10 19:08 UTC, sayas01 commented on src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
> +        this.verifier.globallyVerify(flags -> Assert.assertEquals(0, flags.size()));
Could make use of `this.verifier.verifyEmpty()` instead.

2018-12-10 19:08 UTC, sayas01 commented on src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
> +    public void counterClockwiseRoundaboutBridgeRightDrivingEnclosedTest()
Love how clear the test names are!

2018-12-10 19:39 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +    public static final String WRONG_VALENCE_INSTRUCTIONS = "This roundabout has the wrong valence. It has a valence of {1,number,#}.";
Nope, just something I didn't catch when copying from RoundaboutClosedLoopCheck.

2018-12-10 19:39 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +                    .filter(currentEdge -> !roundaboutEdges.contains(currentEdge))
Agreed. This is an artifact of the old code that just got moved. I will update it.

2018-12-10 19:39 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
>          // or greater than or equal to the maximum configured number of connections
Yep, I missed that one.

2018-12-10 19:39 UTC, Bentleysb commented on src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java
> +        this.verifier.globallyVerify(flags -> Assert.assertEquals(0, flags.size()));
I actually prefer this, as it gives a more useful error message.

2018-12-10 21:19 UTC, sayas01 commented on docs/checks/roundaboutValenceCheck.md
> +each Nodes's connected non-roundabout edges. These connected non-roundabout Edges must also be
`count **of** each`

2018-12-10 21:19 UTC, sayas01 commented on docs/checks/roundaboutValenceCheck.md
> +Once we have retrieved and stored all edges in the roundabout, we iterate over connected Node to get the count
`connected node**s**`

2018-12-10 21:19 UTC, sayas01 commented on docs/checks/roundaboutValenceCheck.md
> +Otherwise the valance of each Node is summed to get the total. If the total is less than the configured minimum (default 2), it is flagged.
typo : valence

2018-12-10 21:20 UTC, sayas01 commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +            final int nodeValance = node.connectedEdges().stream()
nit : nodeValence

2018-12-10 21:27 UTC, sayas01 approved these changes
Nice!

2018-12-11 22:26 UTC, nachtm requested changes
Cool cool cool! Just a couple of nits/suggestions:

2018-12-11 22:26 UTC, nachtm commented on docs/checks/malformedRoundaboutCheck.md
> +This finds items that are generally to large or complex to be considered roundabouts, roundabouts where the wrong ways/edges have been tagged as `junction=roundabout`,
nit: too large

2018-12-11 22:26 UTC, nachtm commented on docs/checks/malformedRoundaboutCheck.md
> +and [throughabouts](https://wiki.openstreetmap.org/wiki/Throughabout) that have benn tagged as roundabouts.
nit: been

2018-12-11 22:26 UTC, nachtm commented on docs/checks/roundaboutValenceCheck.md
> +defined as less than 2. However, this values is configurable, and can be
nit: this value

2018-12-11 22:26 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +                throw new CoreException("Non-ring roundabout");
I'm not a huge fan of using exceptions for flow control like this. Could we refactor?

2018-12-11 22:26 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        return clockwiseCount > counterClockwiseCount ? RoundaboutDirection.CLOCKWISE
I'm having trouble envisioning a valid roundabout with some segments going clockwise and others going counterclockwise. Do you have an example?

2018-12-11 22:26 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +    private boolean roundaboutEnclosesRoads(final Route roundabout)
Nice!

2018-12-11 22:26 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> +        final Set<Edge> roundaboutEdges = new SimpleEdgeWalker(edge, this.isRoundaboutEdge())
Love the `SimpleEdgeWalker`!

2018-12-11 22:40 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        return clockwiseCount > counterClockwiseCount ? RoundaboutDirection.CLOCKWISE
https://www.openstreetmap.org/way/469065666
The NNW flat bit is 2 segments that are slightly concave. Thus the algorithm calculates that one of the segments is clockwise, when the rest are counterclockwise. 
It was found this was causing a lot of false positives, especially with ovoid or triangular roundabouts.

2018-12-12 00:18 UTC, nachtm commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        return clockwiseCount > counterClockwiseCount ? RoundaboutDirection.CLOCKWISE
Ohhhhh I see. Thanks for explaining!

2018-12-12 00:23 UTC, nachtm approved these changes
🆒 🆒 🆒 ❗️

2018-12-13 16:56 UTC, danielduhh approved these changes
Looks great - very nice job.

Can you add some of the overlap statistics to the PR comment? Would be helpful to add the ven-diagram as well

2018-12-13 16:56 UTC, danielduhh commented on docs/checks/malformedRoundaboutCheck.md
> +1. the directionality is opposite to what it should be (for example, a counterclockwise roundabout in a right-driving country)
nit: Capital letter

2018-12-13 16:56 UTC, danielduhh commented on docs/checks/malformedRoundaboutCheck.md
> +2. the segments are multi-directional
nit: Capital letter

2018-12-13 16:56 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        roundaboutEdgeSet
Can you just piece this with the SimpleWalker initialization ?

2018-12-13 16:56 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutValenceCheck.java
> + * turning point, and no connections is obviously not a valid way. In addition no individual Node
nit: In addition,

2018-12-13 17:47 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +        roundaboutEdgeSet
I could individual mark the first edge and then get the rest as they pass through `isRoundaboutEdge`.

2018-12-17 17:59 UTC, closed without merging