Map Roulette Configuration Full URL Parsing Bug
Bentleysb/atlas-checks pull request #33
Opened 2019-04-22 16:54 UTC by Bentleysb

### Description:

This fixes a bug with the MapRouletteConfiguration.parse() method. `:` was used as the delimiter for spiting a string congaing map roulette server connection information. This meant that it would break if it encountered a URL that contained `https://` because it would split the server address on the `:`. This PR changes the delimiter to be a regex expression that checks that `:` is not procedded by `https` or `http`.

### Potential Impact:

http and https map roulette URL's can be used.

### Unit Test Approach:

Added a unit test that includes a https server URL.

### Test Results:

none

2019-04-22 17:35 UTC, danielduhh approved these changes
Super clean ! Going to run some tests real quick... hang tight

2019-04-22 17:39 UTC, sayas01 approved these changes
Nice use of regex!

2019-04-22 22:59 UTC, danielduhh requested changes
Did you get this to work?
I'm getting the following errors
```java
org.openstreetmap.atlas.exception.CoreException: https: nodename nor servname provided, or not known
	at org.openstreetmap.atlas.streaming.resource.http.HttpResource.onRead(HttpResource.java:182)
	at org.openstreetmap.atlas.streaming.resource.http.HttpResource.getStatusCode(HttpResource.java:118)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteConnection.lambda$isAbleToConnectToMapRoulette$0(MapRouletteConnection.java:227)
	at org.openstreetmap.atlas.utilities.runtime.Retry.run(Retry.java:170)
	at org.openstreetmap.atlas.utilities.runtime.Retry.run(Retry.java:104)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteConnection.isAbleToConnectToMapRoulette(MapRouletteConnection.java:222)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteConnection.<init>(MapRouletteConnection.java:52)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteClient.<init>(MapRouletteClient.java:77)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteCommand.onRun(MapRouletteCommand.java:93)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteCommand.onRun(MapRouletteCommand.java:82)
```
This is failing here
https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java#L224
because this.getServer() returns `https://maproulette.....`

2019-04-22 23:08 UTC, Bentleysb commented
Ah, I was just using unit test, and apparently there aren't any that pick this up.

2019-04-22 23:23 UTC, Bentleysb commented
@danielduhh, give it a go now.

2019-04-22 23:42 UTC, Bentleysb commented
@danielduhh, never mind. I just found another spot that needs updates.

2019-04-23 18:31 UTC, Bentleysb commented
Ok @danielduhh, I've change around my approach. See if it works/what you think.

2019-04-26 17:36 UTC, danielduhh commented
Throws a NPE when leaving the port out of the connect args. Can we use a default, or catch this error?
```java
-logfiles=/Users/danielbaah/OSM/data-release/official/48832989/flag/ISL
-maproulette=https://maproulette2.geo.apple.com:daniels_test_project:114|a69554eb-df24-4e40-9040-12f79ef3b367
-projectDisplayName="ssl test"
```
```
java.lang.NullPointerException
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteCommand.fromCommandMap(MapRouletteCommand.java:128)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteCommand.onRun(MapRouletteCommand.java:88)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteCommand.onRun(MapRouletteCommand.java:82)
	at org.openstreetmap.atlas.utilities.runtime.Command.execute(Command.java:338)
	at org.openstreetmap.atlas.utilities.runtime.Command.run(Command.java:282)
	at org.openstreetmap.atlas.checks.maproulette.MapRouletteUploadCommand.main(MapRouletteUploadCommand.java:211)

Process finished with exit code 1
```

2019-04-26 17:50 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConfiguration.java
>          return null;
@danielduhh, here is the source of your NPE. It should have output the logger message from the line above. It is possible we could return a non-zero exit code instead of the NPE, but that would mean funneling back through a couple methods. We could also raise a CoreException in place of the NPE. Any of that sound attractive?

2019-04-26 17:53 UTC, danielduhh commented
Changing the port to 443 works

2019-04-26 17:54 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConfiguration.java
>          return null;
Yeah, Core Exception sounds okay

2019-04-26 21:05 UTC, danielduhh approved these changes

2019-04-26 21:08 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/maproulette/MapRouletteConnection.java
> +                    final String serverConnection = configuration.getScheme() + "://"
`String.format() would be cleaner here`

2019-04-30 17:38 UTC, closed without merging