Intersecting Building Check Enhancments Review
Bentleysb/atlas-checks pull request #9
Opened 2018-06-01 22:52 UTC by Bentleysb

The enhancements made to the Intersecting Building check reworked the way an overlap was defined. Previously an overlap was defined by having one area completely surrounding or matching another. Now overlap is defined as areas of the exact same dimensions. Intersections where one area surrounds another are now defined as 'contains'. 
The configurable `overlap.lower.limit` was removed to accommodate this change. It is now a static `1.0`, or complete area match.

2018-06-01 22:56 UTC, danielduhh commented
Nice!!!!!!!!!!!!

2018-06-01 23:05 UTC, danielduhh requested changes
Nice work B - just some minor requests.

2018-06-01 23:05 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> +                if (((Area) object).asPolygon().surface()
This can be consolidated into `isLargerThan || isGreaterThan`.... There's also an `.equals` function

2018-06-01 23:05 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> +                if (((Area) object).asPolygon().surface()
Also, .surface is called multiple times, which could be an expensive operation; I think you can figure out a way to limit that to 1.

2018-06-01 23:05 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    /*
Any reason for removing the original comment?

2018-06-01 23:05 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    private static final double OVERLAP_LOWER_LIMIT_DEFAULT = 0.90;
I think we should keep the configurable value but change the default to 1.0 & in the config

2018-06-01 23:36 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    /*
It was not true, as the value was not 2%. Before and after enhancement the value default is 1%, and it is configurable so there is no point in having a set value stated in the comment. The new comment is far more accurate.

2018-06-01 23:40 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    private static final double OVERLAP_LOWER_LIMIT_DEFAULT = 0.90;
The reason this was removed as a configurable is that `overlap` is now only true if it is at `1.0`. The single configurable for intersection lower limit now essentially handling what the 2 configurables did before, because of the change to using `contains` instead of `overlap` for many situations.

2018-06-01 23:42 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> +                if (((Area) object).asPolygon().surface()
This cannot be made `isLargerThan || isGreaterThan` because it changes the order of the osm identifiers in the instruction based on which is true.

2018-06-01 23:44 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    private static final double OVERLAP_LOWER_LIMIT_DEFAULT = 0.90;
Okay, if thats the case - the limit variable is a constant & should be capitalized

2018-06-01 23:46 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> +                if (((Area) object).asPolygon().surface()
Ah, ic. The id's are reversed.

2018-06-01 23:51 UTC, Bentleysb commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> -    private static final double OVERLAP_LOWER_LIMIT_DEFAULT = 0.90;
Done

2018-06-04 18:17 UTC, danielduhh requested changes
Couple minor requests & it should be good to go

2018-06-04 18:17 UTC, danielduhh commented on src/test/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheckTest.java
> +    public void containsBuildingAtlas()
Rename function to `testContainsBuildingAtlas` for consistency

2018-06-04 18:17 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java
> +                if (objectAsSurface.isLargerThan(otherBuilding.asPolygon().surface()))
Please add comments to clarify whats going on here

2018-06-04 18:38 UTC, danielduhh approved these changes

2018-06-04 18:45 UTC, closed without merging